---
title: "viz_eda_2"
author: "Kaila Boyer"
date: "10/7/2021"
output: github_document
---

```{r include = FALSE}
library(tidyverse)
library(ggridges)
```

Can include code in the beginning of a document that sets the themes/settings/color for all ggplots 
(look at lecture page on website for code)

Loading in dataset 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

tmax vs. tmin 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Date from noaa package with three stations")
```


## Scales 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Date from noaa package with three stations") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  )
```

## Color Scales 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Data from noaa package with three stations") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  ) + 
  scale_color_hue(
    name = "Location", 
    h = c(100,300))

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Data from noaa package with three stations") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  ) + 
  scale_color_hue(
    name = "Location") +
  scale_color_viridis_d()
```

## Themes 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Data from noaa package with three stations") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  ) + 
  scale_color_hue(
    name = "Location", 
    h = c(100,300)) + 
  scale_color_viridis_d() +
  theme_bw() +
  theme(legend.position = "bottom") 


weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Data from noaa package with three stations") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  ) + 
  scale_color_hue(
    name = "Location", 
    h = c(100,300)) + 
  scale_color_viridis_d() +
  theme_classic() +
  theme(legend.position = "bottom") 

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs( 
    title = "Temperature at three stations", 
    x = "Minimum daily temp (C)", 
    y = "Maximum daily temp (C)", 
    caption = "Data from noaa package with three stations" 
    ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0", "15 C")
  ) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  ) + 
  scale_color_hue(
    name = "Location", 
    h = c(100,300)) + 
  scale_color_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom") 
  
```






