---
title: "viz_eda_1"
author: "Kaila Boyer"
date: "10/5/2021"
output: github_document
---


```{r include = FALSE}
library(tidyverse)
library(ggridges)
```

Loading in dataset 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatter plots

tmax vs. tmin 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() 
```

can save ggplots  
```{r}
gg_tmax_tmin <- weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() 
```

## Adding things to scatter plots 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE) 

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3) + 
  geom_smooth(se = FALSE) 

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(, alpha = 0.3) + 
  geom_smooth(se = FALSE) + 
  facet_grid( . ~ name)
```

One more scatter plot 
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = 0.3) + 
  facet_grid(. ~ name) + 
  geom_smooth(se = FALSE) 
```

## Let's data manipulation as part of this 

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32, 
    tmin = tmin * (9/5) + 32
  ) %>% 
  ggplot(aes(x = date, y = tmax)) + 
  geom_point() 
```

## Stack geoms 

which geoms do you want? 

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_smooth()
```

With hexbins 
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_bin_2d()
```










